src/routes/web.php
<?php

use App\Http\Controllers\Admin\Dashboard\DashboardController;
use App\Http\Controllers\Admin\Report\ReportController;
use App\Http\Controllers\Admin\UrlShortener\UrlShortenerController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes([
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::prefix('admin')->as('admin.')->middleware('auth')->group(function () {
    // DASHBOARD
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    // URL SHORTENER
    Route::resource('/url-shorteners', UrlShortenerController::class);
    // REPORTS
    Route::resource('/reports', ReportController::class);
});

Route::get('/{short_key}', [HomeController::class, 'shortUrl'])->name('short_url');

src/app/Http/Controllers/Admin/UrlShortener/UrlShortenerController.php
<?php

namespace App\Http\Controllers\Admin\UrlShortener;

use App\Http\Controllers\Controller;
use App\Http\Requests\UrlShortener\CreateRequest;
use App\Models\UrlShortner;
use Carbon\Carbon;
use Illuminate\Http\Request;
use BaconQrCode\Renderer\ImageRenderer;
use BaconQrCode\Renderer\Image\ImagickImageBackEnd;
use BaconQrCode\Renderer\RendererStyle\RendererStyle;
use BaconQrCode\Writer;
use URL;

class UrlShortenerController extends Controller
{
    private function generateShortKey() {
        $result = base_convert(time(), 10, 36);
        $check_key = UrlShortner::where('short_key', $result)->first();
        if(!empty($check_key)) {
            $this->generateShortKey();
        }
        return $result;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        set_page_meta('Url Shortener List');
        $url_shorteners = UrlShortner::where('user_id', auth()->user()->id)->get();
        return view('admin.url_shortener.index', compact('url_shorteners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        set_page_meta('Url Shortener Create');
        return view('admin.url_shortener.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
       $url = UrlShortner::where(['url' => $request->url, 'user_id' => auth()->user()->id])->first();
       if(empty($url)) {
        $short_key = $this->generateShortKey();
        $expire_date = null;
        if($request->expire_date) {
            $expire_date = Carbon::parse($request->expire_date)->format('Y-m-d');
        }
        $url = UrlShortner::create([
            'url' => $request->url,
            'user_id' => auth()->user()->id,
            'short_key' => $short_key,
            'hit_limit' => $request->hit_limit,
            'hit_time_limit' => $request->hit_time_limit,
            'block_time' => $request->block_time,
            'expire_date' => $expire_date,
        ]);

        //generate qrcode
        $renderer = new ImageRenderer(
            new RendererStyle(400),
            new ImagickImageBackEnd()
        );
        $writer = new Writer($renderer);
        $writer->writeFile(URL::to('/'.$short_key), public_path('qrcode/'.$short_key.'.png'));
       }

       return redirect()->route('admin.url-shorteners.show', $url->id);
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        set_page_meta('Url Shortener Show');
        $url = UrlShortner::find($id);
        return view('admin.url_shortener.show', compact('url'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        UrlShortner::destroy($id);
        flash('Successfully Deleted!')->success();
        return back();
    }
}

src/resources/views/admin/url_shortener/create.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="page-title-box">
        <div class="row align-items-center">
            <div class="col-sm-6">
                <h4 class="page-title">Add Url Shortener</h4>
            </div>
        </div>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{!! $error !!}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body m-t-10">
                    <form action="{{ route('admin.url-shorteners.store') }}" method="post">
                        @csrf
                        <div class="col-lg-12">
                            <div class="form-group row">
                                <label for="name" class="col-lg-2 col-sm-12 col-form-label">Url</label>
                                <div class="col-lg-6 col-sm-12">
                                    <input type="url" value="{{ old('url') }}" class="form-control" name="url" placeholder="Enter your url" autofocus required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-lg-2 col-sm-12 col-form-label">Hit</label>
                                <div class="col-lg-6 col-sm-12">
                                    <input type="number" value="{{ old('hit_limit') }}" class="form-control" name="hit_limit" placeholder="Enter url hit limit" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-lg-2 col-sm-12 col-form-label">Per Miniute</label>
                                <div class="col-lg-6 col-sm-12">
                                    <input type="number" value="{{ old('hit_time_limit') }}" class="form-control" name="hit_time_limit" placeholder="Enter url hit per miniute" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-lg-2 col-sm-12 col-form-label">Block Time</label>
                                <div class="col-lg-6 col-sm-12">
                                    <input type="number" value="{{ old('block_time') }}" class="form-control" name="block_time" placeholder="Enter block miniute" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-lg-2 col-sm-12 col-form-label">Expire Date</label>
                                <div class="col-lg-6 col-sm-12">
                                    <input type="radio" name="expire_time" onclick="checkExpire('yes')" value="yes"> Yes &nbsp;&nbsp;&nbsp;&nbsp;
                                    <input type="radio" name="expire_time" checked onclick="checkExpire('no')" value="no"> No
                                    <br>
                                    <br>
                                    <input type="date" value="{{ old('expire_date') }}" class="form-control expire_date d-none" name="expire_date" placeholder="Enter expire date">
                                </div>
                            </div>

                            <div class="form-group">
                                <div>
                                    <button class="btn btn-primary waves-effect waves-lightml-2" type="submit">
                                        <i class="fa fa-save"></i> Submit
                                    </button>
                                    <a class="btn btn-secondary waves-effect" href="{{ route('admin.url-shorteners.index') }}">
                                        <i class="fa fa-times"></i> Cancel
                                    </a>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('script')
    <script>
        function checkExpire(val) {
           if(val == 'yes') {
               $('.expire_date').removeClass('d-none');
               $('.expire_date').attr('required', 'true');
           }else {
            $('.expire_date').addClass('d-none');
            $('.expire_date').prop('required',false);
           }
        }
    </script>
@endpush

src/resources/views/admin/url_shortener/index.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="page-title-box">
        <div class="row align-items-center">
            <div class="col-sm-6">
                <h4 class="page-title">Url Shortener List</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="col-md-12 pl-0 mb-2">
                        <a href="{{route('admin.url-shorteners.create')}}" class="btn btn-primary btn-sm float-right"><i class="fa fa-plus"></i> Create Short Url</a>
                    </div>
                    <br>
                    <br>
                    <div class="dt-responsive table-responsive">
                        <table id="basic-btn" class="table table-striped table-bordered nowrap">
                            <thead>
                            <tr>
                                <th>#SL</th>
                                <th>Destination</th>
                                <th>Hit Limit</th>
                                <th>Per Minute</th>
                                <th>Block Minute</th>
                                <th>Expire Date</th>
                                <th>Action</th>
                            </tr>
                            </thead>

                            <tbody>
                            @if($url_shorteners)
                                @foreach($url_shorteners as $key => $url_shortener)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $url_shortener->url }}</td>
                                        <td>{{ $url_shortener->hit_limit }}</td>
                                        <td>{{ $url_shortener->hit_time_limit }}</td>
                                        <td>{{ $url_shortener->block_time }}</td>
                                        <td>{{ $url_shortener->expire_date? Carbon\Carbon::parse($url_shortener->expire_date)->format('M d Y') : 'N/A' }}</td>
                                        <td class="text-center">
                                            <a href="#" onclick="return false;" class="dropdown-toggle dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v"></i>
                                            </a>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item btn btn-sm btn-info" href="{{route('admin.url-shorteners.show', $url_shortener->id)}}"><i class="fa fa-eye"></i> show</a>
                                                <form action="{{ route('admin.url-shorteners.destroy', $url_shortener->id) }}" id="delete-form-{{ $url_shortener->id }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="dropdown-item btn btn-sm btn-danger" onclick="return makeDeleteRequest(event, {{ $url_shortener->id }})" type="submit" title="Delete">
                                                        <i class="fas fa-trash"></i>
                                                        Delete
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div> <!-- end col -->
    </div>

@endsection
@push('style')
    @include('admin.includes.styles.datatable')
@endpush

@push('script')
    @include('admin.includes.scripts.datatable')
@endpush

src/resources/views/admin/url_shortener/show.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="page-title-box">
        <div class="row align-items-center">
            <div class="col-sm-6">
                <h4 class="page-title">Your short url</h4>
            </div>
        </div>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{!! $error !!}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body m-t-10">
                    <a href="{{ URL::to('/'.$url->short_key) }}" target="_blank" rel="noopener noreferrer">{{ URL::to('/'.$url->short_key) }}</a>
                    <br>
                    <img src="{{  URL::to('/').'/qrcode/'.$url->short_key.'.png' }}" alt="no-qrcode" srcset="" width="20%" height="20%">
                </div>
            </div>
        </div>
    </div>

@endsection