src/routes/web.php
<?php

use App\Http\Controllers\Admin\Dashboard\DashboardController;
use App\Http\Controllers\Admin\Report\ReportController;
use App\Http\Controllers\Admin\UrlShortener\UrlShortenerController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes([
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::prefix('admin')->as('admin.')->middleware('auth')->group(function () {
    // DASHBOARD
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    // URL SHORTENER
    Route::resource('/url-shorteners', UrlShortenerController::class);
    // REPORTS
    Route::resource('/reports', ReportController::class);
});

Route::get('/{short_key}', [HomeController::class, 'shortUrl'])->name('short_url');

src/resources/views/admin/layouts/partials/_footer-script.blade.php
<!-- Required Jquery -->
<script type="text/javascript" src="{{ asset('/') }}adminity/files/bower_components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="{{ asset('/') }}adminity/files/bower_components/jquery-ui/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{ asset('/') }}adminity/files/bower_components/popper.js/dist/umd/popper.min.js"></script>
<script type="text/javascript" src="{{ asset('/') }}adminity/files/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- jquery slimscroll js -->
<script type="text/javascript" src="{{ asset('/') }}adminity/files/bower_components/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- modernizr js -->
<script type="text/javascript" src="{{ asset('/') }}adminity/files/bower_components/modernizr/modernizr.js"></script>
<script type="text/javascript" src="{{ asset('/') }}adminity/files/bower_components/modernizr/feature-detects/css-scrollbars.js"></script>
<!-- Chart js -->
<script type="text/javascript" src="{{ asset('/') }}adminity/files/bower_components/chart.js/dist/Chart.js"></script>
<!-- amchart js -->
<script src="{{ asset('/') }}adminity/files/assets/pages/widget/amchart/amcharts.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/widget/amchart/serial.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/pages/widget/amchart/light.js"></script>
<!-- Custom js -->
<script type="text/javascript" src="{{ asset('/') }}adminity/files/assets/js/SmoothScroll.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/js/pcoded.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="{{ asset('/') }}adminity/files/assets/js/vartical-layout.min.js"></script>
<script type="text/javascript" src="{{ asset('/') }}adminity/files/assets/pages/dashboard/analytic-dashboard.min.js"></script>
<script type="text/javascript" src="{{ asset('/') }}adminity/files/assets/js/script.js"></script>

<!-- Sweet-Alert  -->
<script src="{{ URL::asset('adminity/files/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script>
    function makeDeleteRequest(event, id) {
        event.preventDefault();
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: "btn btn-success",
                cancelButton: "btn btn-danger mr-2"
            },
            buttonsStyling: false
        });
        swalWithBootstrapButtons
            .fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                type: "warning",
                showCancelButton: true,
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "No, cancel!",
                reverseButtons: true
            })
            .then(result => {
                console.log(id);
                if (result.value) {
                    let form_id = $("#delete-form-" + id);
                    $(form_id).submit();
                }
            });
    }
</script>

{{-- <script>
    $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
</script> --}}

@stack('script')

src/resources/views/admin/layouts/partials/_head.blade.php
<meta name="csrf-token" content="{{ csrf_token() }}">
<title>{{ get_page_meta() }} {{ config('app.name') }}</title>
<!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 10]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- Favicon icon -->
<link rel="icon" href="{{ asset('/') }}adminity/files/assets/images/favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
<!-- Google font-->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
<!-- Required Framework -->
<link rel="stylesheet" type="text/css" href="{{ asset('/') }}adminity/files/bower_components/bootstrap/dist/css/bootstrap.min.css">
<!-- feather Awesome -->
<link rel="stylesheet" type="text/css" href="{{ asset('/') }}adminity/files/assets/icon/feather/css/feather.css">
<!-- Style.css -->
<link rel="stylesheet" type="text/css" href="{{ asset('/') }}adminity/files/assets/css/style.css">
<link rel="stylesheet" type="text/css" href="{{ asset('/') }}adminity/files/assets/css/jquery.mCustomScrollbar.css">
<!-- Sweet Alert -->
<link href="{{ URL::asset('adminity/files/plugins/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
<style type="text/css">
    .dropdown-toggle::after {
        display: none;
    }
</style>
@stack('style')

src/resources/views/admin/layouts/partials/_header.blade.php
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">

        <div class="navbar-logo">
            <a class="mobile-menu" id="mobile-collapse" href="#!">
                <i class="feather icon-menu"></i>
            </a>
            <a href="#">
                URL SHORTENER
            </a>
            <a class="mobile-options">
                <i class="feather icon-more-horizontal"></i>
            </a>
        </div>

        <div class="navbar-container">
            <ul class="nav-left">
                <li>
                    <a href="#!" onclick="javascript:toggleFullScreen()">
                        <i class="feather icon-maximize full-screen"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav-right">
                <li class="user-profile header-notification">
                    <div class="dropdown-primary dropdown">
                        <div class="dropdown-toggle" data-toggle="dropdown">
                            <span>{{ auth()->user()->name }}</span>
                            <i class="feather icon-chevron-down"></i>
                        </div>
                        <ul class="show-notification profile-notification dropdown-menu"
                            data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                       document.getElementById('logout-form').submit();">
                                    <i class="feather icon-log-out"></i> Logout
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>

                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

src/resources/views/admin/layouts/partials/_sidebar.blade.php
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu">
        <div class="pcoded-navigatio-lavel">Navigation</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="active pcoded-trigger">
                <a href="{{ route('admin.dashboard') }}">
                    <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                    <span class="pcoded-mtext">Dashboard</span>
                </a>
            </li>
            <li class="pcoded">
                <a href="{{ route('admin.url-shorteners.index') }}">
                    <span class="pcoded-micon"><i class="feather icon-sidebar"></i></span>
                    <span class="pcoded-mtext">Url Shortener</span>
                </a>
            </li>
            <li class="pcoded">
                <a href="{{ route('admin.reports.index') }}">
                    <span class="pcoded-micon"><i class="feather icon-sidebar"></i></span>
                    <span class="pcoded-mtext">Reports</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

src/resources/views/admin/layouts/partials/dashboard_box.blade.php
<div class="page-wrapper">
    <div class="page-body">
        <div class="row">
            <!-- task, page, download counter  start -->
            <div class="col-xl-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h4 class="text-c-yellow f-w-600">$30200</h4>
                                <h6 class="text-muted m-b-0">All Earnings</h6>
                            </div>
                            <div class="col-4 text-right">
                                <i class="feather icon-bar-chart f-28"></i>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-c-yellow">
                        <div class="row align-items-center">
                            <div class="col-9">
                                <p class="text-white m-b-0">% change</p>
                            </div>
                            <div class="col-3 text-right">
                                <i class="feather icon-trending-up text-white f-16"></i>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h4 class="text-c-green f-w-600">290+</h4>
                                <h6 class="text-muted m-b-0">Page Views</h6>
                            </div>
                            <div class="col-4 text-right">
                                <i class="feather icon-file-text f-28"></i>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-c-green">
                        <div class="row align-items-center">
                            <div class="col-9">
                                <p class="text-white m-b-0">% change</p>
                            </div>
                            <div class="col-3 text-right">
                                <i class="feather icon-trending-up text-white f-16"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h4 class="text-c-pink f-w-600">145</h4>
                                <h6 class="text-muted m-b-0">Task Completed</h6>
                            </div>
                            <div class="col-4 text-right">
                                <i class="feather icon-calendar f-28"></i>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-c-pink">
                        <div class="row align-items-center">
                            <div class="col-9">
                                <p class="text-white m-b-0">% change</p>
                            </div>
                            <div class="col-3 text-right">
                                <i class="feather icon-trending-up text-white f-16"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-6">
                <div class="card">
                    <div class="card-block">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h4 class="text-c-blue f-w-600">500</h4>
                                <h6 class="text-muted m-b-0">Downloads</h6>
                            </div>
                            <div class="col-4 text-right">
                                <i class="feather icon-download f-28"></i>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-c-blue">
                        <div class="row align-items-center">
                            <div class="col-9">
                                <p class="text-white m-b-0">% change</p>
                            </div>
                            <div class="col-3 text-right">
                                <i class="feather icon-trending-up text-white f-16"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- task, page, download counter  end -->
        </div>
    </div>
</div>

src/resources/views/admin/layouts/partials/preloader.blade.php
<!-- Pre-loader start -->
<div class="theme-loader">
    <div class="ball-scale">
        <div class='contain'>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
            <div class="ring">
                <div class="frame"></div>
            </div>
        </div>
    </div>
</div>
<!-- Pre-loader end -->